# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "capsaicin"
  s.version = "0.1.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joe Khoobyar"]
  s.date = "2013-02-19"
  s.description = "Spicy capistrano extensions for various needs"
  s.email = "joe@ankhcraft.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "capsaicin.gemspec",
    "lib/capistrano/recipes/deploy/strategy/copy_package.rb",
    "lib/capsaicin.rb",
    "lib/capsaicin/bundle.rb",
    "lib/capsaicin/files.rb",
    "lib/capsaicin/files/local.rb",
    "lib/capsaicin/files/remote.rb",
    "lib/capsaicin/invocation.rb",
    "lib/capsaicin/namespace.rb",
    "lib/capsaicin/pom.rb",
    "lib/capsaicin/service.rb",
    "lib/capsaicin/service/command.rb",
    "lib/capsaicin/service/crm.rb",
    "lib/capsaicin/service/lsb.rb",
    "lib/capsaicin/service/windows.rb",
    "lib/capsaicin/sys.rb",
    "lib/capsaicin/ui.rb",
    "test/capsaicin/files/local_test.rb",
    "test/capsaicin/invocation_test.rb",
    "test/helper.rb"
  ]
  s.homepage = "http://github.com/joekhoobyar/capsaicin"
  s.require_paths = ["lib"]
  s.rubyforge_project = "capsaicin"
  s.rubygems_version = "1.8.11"
  s.summary = "Joe Khoobyar's spicy capistrano extensions"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 2.5"])
      s.add_runtime_dependency(%q<archive-tar-minitar>, [">= 0.5"])
    else
      s.add_dependency(%q<capistrano>, [">= 2.5"])
      s.add_dependency(%q<archive-tar-minitar>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 2.5"])
    s.add_dependency(%q<archive-tar-minitar>, [">= 0.5"])
  end
end

